site_name: Hallllow29 - Portfolio
site_description: CTF writeups, projects and security notes
site_author: Hallllow29

repo_name: hallllow29/cybersecurity-portfolio
repo_url: https://github.com/hallllow29/cybersecurity-portfolio
site_url: https://hallllow29.github.io/cybersecurity-portfolio

theme:
  name: material
  palette:
    scheme: default
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest
  font:
    code: Roboto Mono

nav:
  - Home: index.md
  - Projects:
      - Overview: projects/index.md

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
