-- Inserir dados na tabela Material (com unidades de medida específicas para calçado em português)
INSERT INTO Material (nome, tipo, unidadeMedida, custoUnitario) VALUES
('Pele Genuína', 'Couro', 'Pé Quadrado', 2.80),
('Sola de Borracha', 'Solas', 'Par', 3.20),
('Atacadores', 'Acessórios', 'Par', 0.50),
('Linha de Costura', 'Fios', 'Carretel', 1.10),
('Cola de Sapato', 'Químicos', 'Litro', 7.80),
('Palmilha', 'Componentes Internos', 'Par', 1.50),
('Tecido Sintético', 'Tecidos', 'Metro Linear', 1.75),
('Fivelas Metálicas', 'Acessórios', 'Unidade', 0.35),
('Fecho Éclair', 'Acessórios', 'Unidade', 0.90),
('Ilhós', 'Acessórios', 'Milheiro', 2.15),
('Reforço Lateral', 'Componentes Internos', 'Par', 0.80),
('Etiquetas', 'Embalagem', 'Unidade', 0.06),
('Caixas de Sapatos', 'Embalagem', 'Unidade', 0.45),
('Não Tecido', 'Tecidos', 'Metro Linear', 0.58),
('Camurça', 'Couro', 'Pé Quadrado', 3.30),
('Verniz', 'Couro', 'Pé Quadrado', 3.10),
('Elástico', 'Acessórios', 'Metro Linear', 0.25),
('Velcro', 'Acessórios', 'Metro Linear', 0.65),
('TNT (Tecido Não Tecido)', 'Tecidos', 'Metro Linear', 0.36),
('Pelúcia Sintética', 'Tecidos', 'Metro Linear', 2.50),
('Pele Ecológica', 'Couro Sintético', 'Pé Quadrado', 1.75),
('Sola de Poliuretano (PU)', 'Solas', 'Par', 4.10),
('Reforço de Biqueira', 'Componentes Internos', 'Par', 0.55),
('Contraforte', 'Componentes Internos', 'Par', 0.70),
('Cola de Poliuretano', 'Químicos', 'Litro', 9.50),
('Tachas', 'Acessórios', 'Milheiro', 13.00),
('Membrana Impermeável', 'Tecidos', 'Metro Linear', 3.70),
('Forro Têxtil', 'Componentes Internos', 'Metro Linear', 0.65),
('Palmilha Ortopédica', 'Componentes Internos', 'Par', 2.80),
('Fio de Nylon', 'Fios', 'Carretel', 1.50),
('Spray Impermeabilizante', 'Químicos', 'Unidade', 5.20),
('Papel de Embrulho', 'Embalagem', 'Metro', 0.10),
('Sacos de Proteção', 'Embalagem', 'Unidade', 0.20),
('Microfibra', 'Tecidos', 'Metro Linear', 1.36),
('Lona', 'Tecidos', 'Metro Linear', 1.43),
('Cortiça', 'Solas', 'Placa', 11.00),
('EVA (Etileno Vinil Acetato)', 'Solas', 'Placa', 12.00),
('Fita Adesiva', 'Embalagem', 'Rolo', 1.90),
('Cartão', 'Embalagem', 'Folha', 0.03),
('Feltro', 'Tecidos', 'Metro Linear', 0.90);