name: Deploy MkDocs site

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install mkdocs and material
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      - name: Generate docs from repo folders
        run: |
          chmod +x ./generate_docs.sh
          ./generate_docs.sh

      - name: Build mkdocs site
        run: |
          mkdocs build --site-dir site

      - name: Deploy to GitHub Pages (gh-pages)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
